/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LockedRouteImport } from './routes/locked'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntryClubIdNfcUidRouteImport } from './routes/entry.$clubId.$nfcUid'
import { Route as ClubClubIdAuthenticatedRouteImport } from './routes/club.$clubId/_authenticated'
import { Route as ClubClubIdAuthenticatedIndexRouteImport } from './routes/club.$clubId/_authenticated/index'
import { Route as ClubClubIdAuthenticatedWalletRouteImport } from './routes/club.$clubId/_authenticated/wallet'
import { Route as ClubClubIdAuthenticatedAdminIndexRouteImport } from './routes/club.$clubId/_authenticated/admin/index'
import { Route as ClubClubIdAuthenticatedPurchaseProductIdRouteImport } from './routes/club.$clubId/_authenticated/purchase.$productId'
import { Route as ClubClubIdAuthenticatedAdminTopupsRouteImport } from './routes/club.$clubId/_authenticated/admin/topups'
import { Route as ClubClubIdAuthenticatedAdminProductsRouteImport } from './routes/club.$clubId/_authenticated/admin/products'
import { Route as ClubClubIdAuthenticatedAdminMembersRouteImport } from './routes/club.$clubId/_authenticated/admin/members'

const LockedRoute = LockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryClubIdNfcUidRoute = EntryClubIdNfcUidRouteImport.update({
  id: '/entry/$clubId/$nfcUid',
  path: '/entry/$clubId/$nfcUid',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubClubIdAuthenticatedRoute = ClubClubIdAuthenticatedRouteImport.update({
  id: '/club/$clubId/_authenticated',
  path: '/club/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubClubIdAuthenticatedIndexRoute =
  ClubClubIdAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ClubClubIdAuthenticatedRoute,
  } as any)
const ClubClubIdAuthenticatedWalletRoute =
  ClubClubIdAuthenticatedWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => ClubClubIdAuthenticatedRoute,
  } as any)
const ClubClubIdAuthenticatedAdminIndexRoute =
  ClubClubIdAuthenticatedAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => ClubClubIdAuthenticatedRoute,
  } as any)
const ClubClubIdAuthenticatedPurchaseProductIdRoute =
  ClubClubIdAuthenticatedPurchaseProductIdRouteImport.update({
    id: '/purchase/$productId',
    path: '/purchase/$productId',
    getParentRoute: () => ClubClubIdAuthenticatedRoute,
  } as any)
const ClubClubIdAuthenticatedAdminTopupsRoute =
  ClubClubIdAuthenticatedAdminTopupsRouteImport.update({
    id: '/admin/topups',
    path: '/admin/topups',
    getParentRoute: () => ClubClubIdAuthenticatedRoute,
  } as any)
const ClubClubIdAuthenticatedAdminProductsRoute =
  ClubClubIdAuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => ClubClubIdAuthenticatedRoute,
  } as any)
const ClubClubIdAuthenticatedAdminMembersRoute =
  ClubClubIdAuthenticatedAdminMembersRouteImport.update({
    id: '/admin/members',
    path: '/admin/members',
    getParentRoute: () => ClubClubIdAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/locked': typeof LockedRoute
  '/club/$clubId': typeof ClubClubIdAuthenticatedRouteWithChildren
  '/entry/$clubId/$nfcUid': typeof EntryClubIdNfcUidRoute
  '/club/$clubId/wallet': typeof ClubClubIdAuthenticatedWalletRoute
  '/club/$clubId/': typeof ClubClubIdAuthenticatedIndexRoute
  '/club/$clubId/admin/members': typeof ClubClubIdAuthenticatedAdminMembersRoute
  '/club/$clubId/admin/products': typeof ClubClubIdAuthenticatedAdminProductsRoute
  '/club/$clubId/admin/topups': typeof ClubClubIdAuthenticatedAdminTopupsRoute
  '/club/$clubId/purchase/$productId': typeof ClubClubIdAuthenticatedPurchaseProductIdRoute
  '/club/$clubId/admin/': typeof ClubClubIdAuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/locked': typeof LockedRoute
  '/entry/$clubId/$nfcUid': typeof EntryClubIdNfcUidRoute
  '/club/$clubId/wallet': typeof ClubClubIdAuthenticatedWalletRoute
  '/club/$clubId': typeof ClubClubIdAuthenticatedIndexRoute
  '/club/$clubId/admin/members': typeof ClubClubIdAuthenticatedAdminMembersRoute
  '/club/$clubId/admin/products': typeof ClubClubIdAuthenticatedAdminProductsRoute
  '/club/$clubId/admin/topups': typeof ClubClubIdAuthenticatedAdminTopupsRoute
  '/club/$clubId/purchase/$productId': typeof ClubClubIdAuthenticatedPurchaseProductIdRoute
  '/club/$clubId/admin': typeof ClubClubIdAuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/locked': typeof LockedRoute
  '/club/$clubId/_authenticated': typeof ClubClubIdAuthenticatedRouteWithChildren
  '/entry/$clubId/$nfcUid': typeof EntryClubIdNfcUidRoute
  '/club/$clubId/_authenticated/wallet': typeof ClubClubIdAuthenticatedWalletRoute
  '/club/$clubId/_authenticated/': typeof ClubClubIdAuthenticatedIndexRoute
  '/club/$clubId/_authenticated/admin/members': typeof ClubClubIdAuthenticatedAdminMembersRoute
  '/club/$clubId/_authenticated/admin/products': typeof ClubClubIdAuthenticatedAdminProductsRoute
  '/club/$clubId/_authenticated/admin/topups': typeof ClubClubIdAuthenticatedAdminTopupsRoute
  '/club/$clubId/_authenticated/purchase/$productId': typeof ClubClubIdAuthenticatedPurchaseProductIdRoute
  '/club/$clubId/_authenticated/admin/': typeof ClubClubIdAuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/locked'
    | '/club/$clubId'
    | '/entry/$clubId/$nfcUid'
    | '/club/$clubId/wallet'
    | '/club/$clubId/'
    | '/club/$clubId/admin/members'
    | '/club/$clubId/admin/products'
    | '/club/$clubId/admin/topups'
    | '/club/$clubId/purchase/$productId'
    | '/club/$clubId/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/locked'
    | '/entry/$clubId/$nfcUid'
    | '/club/$clubId/wallet'
    | '/club/$clubId'
    | '/club/$clubId/admin/members'
    | '/club/$clubId/admin/products'
    | '/club/$clubId/admin/topups'
    | '/club/$clubId/purchase/$productId'
    | '/club/$clubId/admin'
  id:
    | '__root__'
    | '/'
    | '/locked'
    | '/club/$clubId/_authenticated'
    | '/entry/$clubId/$nfcUid'
    | '/club/$clubId/_authenticated/wallet'
    | '/club/$clubId/_authenticated/'
    | '/club/$clubId/_authenticated/admin/members'
    | '/club/$clubId/_authenticated/admin/products'
    | '/club/$clubId/_authenticated/admin/topups'
    | '/club/$clubId/_authenticated/purchase/$productId'
    | '/club/$clubId/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LockedRoute: typeof LockedRoute
  ClubClubIdAuthenticatedRoute: typeof ClubClubIdAuthenticatedRouteWithChildren
  EntryClubIdNfcUidRoute: typeof EntryClubIdNfcUidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/locked': {
      id: '/locked'
      path: '/locked'
      fullPath: '/locked'
      preLoaderRoute: typeof LockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/$clubId/$nfcUid': {
      id: '/entry/$clubId/$nfcUid'
      path: '/entry/$clubId/$nfcUid'
      fullPath: '/entry/$clubId/$nfcUid'
      preLoaderRoute: typeof EntryClubIdNfcUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/$clubId/_authenticated': {
      id: '/club/$clubId/_authenticated'
      path: '/club/$clubId'
      fullPath: '/club/$clubId'
      preLoaderRoute: typeof ClubClubIdAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/$clubId/_authenticated/': {
      id: '/club/$clubId/_authenticated/'
      path: '/'
      fullPath: '/club/$clubId/'
      preLoaderRoute: typeof ClubClubIdAuthenticatedIndexRouteImport
      parentRoute: typeof ClubClubIdAuthenticatedRoute
    }
    '/club/$clubId/_authenticated/wallet': {
      id: '/club/$clubId/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/club/$clubId/wallet'
      preLoaderRoute: typeof ClubClubIdAuthenticatedWalletRouteImport
      parentRoute: typeof ClubClubIdAuthenticatedRoute
    }
    '/club/$clubId/_authenticated/admin/': {
      id: '/club/$clubId/_authenticated/admin/'
      path: '/admin'
      fullPath: '/club/$clubId/admin/'
      preLoaderRoute: typeof ClubClubIdAuthenticatedAdminIndexRouteImport
      parentRoute: typeof ClubClubIdAuthenticatedRoute
    }
    '/club/$clubId/_authenticated/purchase/$productId': {
      id: '/club/$clubId/_authenticated/purchase/$productId'
      path: '/purchase/$productId'
      fullPath: '/club/$clubId/purchase/$productId'
      preLoaderRoute: typeof ClubClubIdAuthenticatedPurchaseProductIdRouteImport
      parentRoute: typeof ClubClubIdAuthenticatedRoute
    }
    '/club/$clubId/_authenticated/admin/topups': {
      id: '/club/$clubId/_authenticated/admin/topups'
      path: '/admin/topups'
      fullPath: '/club/$clubId/admin/topups'
      preLoaderRoute: typeof ClubClubIdAuthenticatedAdminTopupsRouteImport
      parentRoute: typeof ClubClubIdAuthenticatedRoute
    }
    '/club/$clubId/_authenticated/admin/products': {
      id: '/club/$clubId/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/club/$clubId/admin/products'
      preLoaderRoute: typeof ClubClubIdAuthenticatedAdminProductsRouteImport
      parentRoute: typeof ClubClubIdAuthenticatedRoute
    }
    '/club/$clubId/_authenticated/admin/members': {
      id: '/club/$clubId/_authenticated/admin/members'
      path: '/admin/members'
      fullPath: '/club/$clubId/admin/members'
      preLoaderRoute: typeof ClubClubIdAuthenticatedAdminMembersRouteImport
      parentRoute: typeof ClubClubIdAuthenticatedRoute
    }
  }
}

interface ClubClubIdAuthenticatedRouteChildren {
  ClubClubIdAuthenticatedWalletRoute: typeof ClubClubIdAuthenticatedWalletRoute
  ClubClubIdAuthenticatedIndexRoute: typeof ClubClubIdAuthenticatedIndexRoute
  ClubClubIdAuthenticatedAdminMembersRoute: typeof ClubClubIdAuthenticatedAdminMembersRoute
  ClubClubIdAuthenticatedAdminProductsRoute: typeof ClubClubIdAuthenticatedAdminProductsRoute
  ClubClubIdAuthenticatedAdminTopupsRoute: typeof ClubClubIdAuthenticatedAdminTopupsRoute
  ClubClubIdAuthenticatedPurchaseProductIdRoute: typeof ClubClubIdAuthenticatedPurchaseProductIdRoute
  ClubClubIdAuthenticatedAdminIndexRoute: typeof ClubClubIdAuthenticatedAdminIndexRoute
}

const ClubClubIdAuthenticatedRouteChildren: ClubClubIdAuthenticatedRouteChildren =
  {
    ClubClubIdAuthenticatedWalletRoute: ClubClubIdAuthenticatedWalletRoute,
    ClubClubIdAuthenticatedIndexRoute: ClubClubIdAuthenticatedIndexRoute,
    ClubClubIdAuthenticatedAdminMembersRoute:
      ClubClubIdAuthenticatedAdminMembersRoute,
    ClubClubIdAuthenticatedAdminProductsRoute:
      ClubClubIdAuthenticatedAdminProductsRoute,
    ClubClubIdAuthenticatedAdminTopupsRoute:
      ClubClubIdAuthenticatedAdminTopupsRoute,
    ClubClubIdAuthenticatedPurchaseProductIdRoute:
      ClubClubIdAuthenticatedPurchaseProductIdRoute,
    ClubClubIdAuthenticatedAdminIndexRoute:
      ClubClubIdAuthenticatedAdminIndexRoute,
  }

const ClubClubIdAuthenticatedRouteWithChildren =
  ClubClubIdAuthenticatedRoute._addFileChildren(
    ClubClubIdAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LockedRoute: LockedRoute,
  ClubClubIdAuthenticatedRoute: ClubClubIdAuthenticatedRouteWithChildren,
  EntryClubIdNfcUidRoute: EntryClubIdNfcUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
